/**
 * Documentation Routes
 *
 * Machine-facing API documentation served under /docs:
 *   GET /docs                        — Interactive API docs (Scalar viewer, public)
 *   GET /docs/SKILL.md               — Agent skill file (public, personalized when authenticated)
 *   GET /docs/gws-client-secret.json — Google Workspace CLI OAuth client config (authenticated or campus)
 *
 * The OpenAPI spec itself is auto-generated by @hono/zod-openapi and served
 * from index.ts via app.doc31(). This file provides the Scalar HTML wrapper,
 * the SKILL.md builder, and the GWS credential distribution endpoint.
 */

import { OpenAPIHono } from '@hono/zod-openapi';
import type { AppEnv, UserKeyRow } from '../types';
import { getModelInfo } from '../openrouter';
import type { ModelCost, ModelCostRaw } from '../openrouter';
import { getSession } from '../utils/session';
import { isCampusPassEligible } from '../utils/ip';
import { BAYLEAF_TOKEN_PREFIX } from '../constants';

export const docsRoutes = new OpenAPIHono<AppEnv>();

// ── GET / — Scalar API reference viewer ───────────────────────────

docsRoutes.get('/', (c) => {
  const html = `<!doctype html>
<html>
<head>
  <title>BayLeaf API Reference</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>
  <script id="api-reference" data-url="/docs/openapi.json"></script>
  <script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>
</body>
</html>`;
  return c.html(html);
});

// ── GET /SKILL.md (authenticated or campus) ───────────────────────

docsRoutes.get('/SKILL.md', async (c) => {
  const user = await resolveDocsUser(c);

  const model = c.env.RECOMMENDED_MODEL;
  const info = await getModelInfo(model);
  const name = info?.name ?? model;
  const cost = info?.cost ?? null;
  const costRaw = info?.costRaw ?? null;
  // Placeholder follows UCSC CruzID convention (the banana slug mascot).
  // ref: https://its.ucsc.edu/services/accounts-and-passwords/ucsc-computing-accounts/cruzid/
  const email = (user && user !== 'campus') ? user : 'bslug@ucsc.edu';
  const gwsEnabled = gwsConfigured(c.env);
  const content = buildSkillMd(model, name, cost, costRaw, email, gwsEnabled);
  return c.text(content, 200, { 'Content-Type': 'text/markdown; charset=utf-8' });
});

// ── Auth helper for docs routes ───────────────────────────────────
//
// GWS endpoints require a session cookie, Bearer sk-bayleaf-* token,
// or campus network access (Campus Pass). SKILL.md is public but
// personalizes the GWS section with the user's email when authenticated.

/**
 * Resolve the user's email from session, Bearer token, or Campus Pass.
 * Returns the email if identified, or 'campus' for anonymous campus users.
 * Returns null if no valid auth is present.
 */
async function resolveDocsUser(c: import('hono').Context<AppEnv>): Promise<string | null> {
  // Try session cookie first (browser users)
  const session = await getSession(c);
  if (session) return session.email;

  // Try Bearer token (agents)
  const authHeader = c.req.header('Authorization');
  const token = authHeader?.replace(/^Bearer\s+/i, '').trim();
  if (token && token.startsWith(BAYLEAF_TOKEN_PREFIX)) {
    const row = await c.env.DB.prepare(
      'SELECT email FROM user_keys WHERE bayleaf_token = ? AND revoked = 0',
    ).bind(token).first<UserKeyRow>();
    if (row) return row.email;
  }

  // Campus Pass (on-campus IP, no credentials needed)
  if (isCampusPassEligible(c.req.raw, c.env)) {
    return 'campus';
  }

  return null;
}

/** Check whether GWS distribution is configured (all three env vars present). */
function gwsConfigured(env: AppEnv['Bindings']): boolean {
  return !!(env.GWS_CLIENT_ID && env.GWS_CLIENT_SECRET && env.GWS_PROJECT_ID);
}

/** Build the client_secret.json from env vars (Google Desktop OAuth format). */
function buildClientSecretJson(env: AppEnv['Bindings']): object {
  return {
    installed: {
      client_id: env.GWS_CLIENT_ID,
      project_id: env.GWS_PROJECT_ID,
      auth_uri: 'https://accounts.google.com/o/oauth2/auth',
      token_uri: 'https://oauth2.googleapis.com/token',
      auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs',
      client_secret: env.GWS_CLIENT_SECRET,
      redirect_uris: ['http://localhost'],
    },
  };
}

docsRoutes.get('/gws-client-secret.json', async (c) => {
  if (!gwsConfigured(c.env)) {
    return c.json({ error: 'Google Workspace CLI distribution is not configured on this deployment.' }, 404);
  }

  const user = await resolveDocsUser(c);
  if (!user) {
    return c.json({ error: 'Authentication required. Sign in at https://api.bayleaf.dev/, use Authorization: Bearer sk-bayleaf-..., or access from the campus network.' }, 401);
  }

  const clientSecret = buildClientSecretJson(c.env);
  return c.json(clientSecret, 200);
});

// ── SKILL.md builder ──────────────────────────────────────────────

function buildSkillMd(model: string, modelName: string, cost: ModelCost | null, costRaw: ModelCostRaw | null, email: string, gwsEnabled: boolean): string {
  const bt = '`';
  const fence = '```';

  return `---
name: bayleaf-api
description: Use the BayLeaf API for LLM inference, sandboxed code execution, and model discovery at UC Santa Cruz.
---

# BayLeaf API

BayLeaf API (${bt}https://api.bayleaf.dev${bt}) provides free LLM inference and sandboxed
code execution for the UC Santa Cruz campus community. All inference uses
zero-data-retention providers — conversations are never used for training.

Full OpenAPI 3.1 spec: ${bt}https://api.bayleaf.dev/docs/openapi.json${bt}

---

## Authentication

All machine-facing endpoints accept ${bt}Authorization: Bearer <key>${bt}.

| Method | When to use |
|--------|-------------|
| **BayLeaf key** (${bt}sk-bayleaf-...${bt}) | Off-campus, or when you need a persistent sandbox and file access. Provision free at ${bt}https://api.bayleaf.dev/${bt}. |
| **Campus Pass** (omit header) | On the UCSC campus network. No key needed. Sandbox access is ephemeral (one-shot). |

Daily spending limit per key: $1 (resets daily). All rate limiting is handled by the
upstream provider — the API itself imposes no request-rate limits.

---

## LLM Inference

BayLeaf is an OpenAI-compatible proxy. Point any OpenAI-compatible client at
${bt}https://api.bayleaf.dev/v1${bt} with your key and it works.

### Chat Completions

${fence}
POST /v1/chat/completions
Content-Type: application/json
Authorization: Bearer sk-bayleaf-...

{
  "model": "${model}",
  "messages": [
    { "role": "user", "content": "Explain the halting problem in one paragraph." }
  ]
}
${fence}

Supports ${bt}stream: true${bt} for SSE streaming. All standard OpenAI parameters
(${bt}temperature${bt}, ${bt}max_tokens${bt}, ${bt}tools${bt}, etc.) are forwarded to OpenRouter.

### Responses API

${fence}
POST /v1/responses
Content-Type: application/json
Authorization: Bearer sk-bayleaf-...

{
  "model": "${model}",
  "input": "What is the capital of France?"
}
${fence}

### Other OpenRouter endpoints

Any ${bt}/v1/*${bt} path is proxied directly to OpenRouter. This includes endpoints like
${bt}/v1/models${bt} (list available models), ${bt}/v1/auth/key${bt} (check your key usage),
and any future OpenRouter endpoints. The proxy does no model filtering — any model
ID accepted by OpenRouter works.

---

## Sandboxed Code Execution

BayLeaf provides sandboxed Linux environments for running code.

### Execute a command

${fence}
POST /sandbox/exec
Content-Type: application/json
Authorization: Bearer sk-bayleaf-...

{
  "command": "python3 -c \\"print(2+2)\\"",
  "workdir": "/home/daytona/workspace"
}
${fence}

Response:

${fence}json
{ "exitCode": 0, "output": "4\\n" }
${fence}

- Commands run under ${bt}set -e -o pipefail${bt} with a 120-second timeout.
- The sandbox is a full Debian-based Linux environment with network access.
- ${bt}workdir${bt} defaults to ${bt}/home/daytona/workspace${bt} if omitted.
- **Keyed users** get a persistent sandbox that survives across requests.
- **Campus Pass users** get an ephemeral sandbox that is created and destroyed per-request.

### Download a file

${fence}
GET /sandbox/files/home/daytona/workspace/output.txt
Authorization: Bearer sk-bayleaf-...
${fence}

Returns the raw file bytes. Requires a BayLeaf API key (persistent sandbox only).

### Upload a file

${fence}
PUT /sandbox/files/home/daytona/workspace/input.txt
Authorization: Bearer sk-bayleaf-...
Content-Type: application/octet-stream

<file bytes>
${fence}

Response:

${fence}json
{ "success": true, "path": "/home/daytona/workspace/input.txt", "bytes": 1234 }
${fence}

Parent directories are created automatically. Requires a BayLeaf API key.

### Destroy sandbox

${fence}
DELETE /sandbox
Authorization: Bearer sk-bayleaf-...
${fence}

Permanently destroys the sandbox and all its data.

---

## Model Recommendation

The recommended model changes over time. Fetch the current recommendation:

${fence}
GET /recommended-model
${fence}

Response:

${fence}json
{ "model": "${model}", "name": "${modelName}" }
${fence}

No authentication required.

---

## OpenCode Setup

To use BayLeaf as an [OpenCode](https://opencode.ai) provider:

### 1. Add provider config

Add to ${bt}~/.config/opencode/opencode.json${bt} (create if needed; merge into existing
${bt}"provider"${bt} object if the file already exists):

${fence}json
{
  "$schema": "https://opencode.ai/config.json",
  "provider": {
    "bayleaf": {
      "npm": "@ai-sdk/openai-compatible",
      "name": "BayLeaf API",
      "options": {
        "baseURL": "https://api.bayleaf.dev/v1"
      },
      "models": {
        "${model}": {
          "name": "${modelName}"${cost ? `,
          "cost": { "input": ${cost.input}, "output": ${cost.output}, "cache_read": ${cost.cacheRead}, "cache_write": ${cost.cacheWrite} }` : ''}
        }
      }
    }
  }
}
${fence}

Restart OpenCode after any config change.

### 2. Store the API key

Run ${bt}/connect${bt} in OpenCode, select **BayLeaf API** (under **Other**), and paste
your ${bt}sk-bayleaf-...${bt} key.

### 3. Select the model

Run ${bt}/models${bt} and select ${bt}${model}${bt} under BayLeaf API.

---

## pi Setup

To use BayLeaf with the [pi coding agent](https://github.com/badlogic/pi-mono)
(${bt}npm install -g @mariozechner/pi-coding-agent${bt}):

### 1. Store the API key

${fence}bash
mkdir -p ~/.tokens && chmod 700 ~/.tokens
echo -n 'sk-bayleaf-...' > ~/.tokens/bayleaf-api
chmod 600 ~/.tokens/bayleaf-api
${fence}

### 2. Add provider config

Create or edit ${bt}~/.pi/agent/models.json${bt}:

${fence}json
{
  "providers": {
    "bayleaf": {
      "baseUrl": "https://api.bayleaf.dev/v1",
      "apiKey": "!cat ~/.tokens/bayleaf-api",
      "api": "openai-completions",
      "models": [
        {
          "id": "${model}",
          "name": "${modelName} (BayLeaf)"${cost ? `,
          "cost": { "input": ${cost.input}, "output": ${cost.output}, "cacheRead": ${cost.cacheRead}, "cacheWrite": ${cost.cacheWrite} }` : ''}
        }
      ]
    }
  }
}
${fence}

The ${bt}!${bt} prefix tells pi to resolve the value by running a shell command.
If you prefer, you can set ${bt}BAYLEAF_API_KEY${bt} in your environment and use
${bt}"apiKey": "BAYLEAF_API_KEY"${bt} instead (pi checks env vars by name before
treating the string as a literal).

### 3. Use the model

${fence}bash
pi --model bayleaf/${model} "Help me refactor this code"
${fence}

Or launch interactively and switch with ${bt}Ctrl+P${bt}:

${fence}bash
pi --model bayleaf/${model}
${fence}

---

## Goose Setup

To use BayLeaf with [Goose](https://github.com/block/goose)
(${bt}curl -fsSL https://github.com/block/goose/releases/latest/download/install.sh | sh${bt}).
Requires Goose **1.29+**.

### 1. Create a custom provider file

Create ${bt}~/.config/goose/custom_providers/bayleaf.json${bt}:

${fence}json
{
  "name": "bayleaf",
  "engine": "openai",
  "display_name": "BayLeaf API",
  "description": "OpenRouter-proxying LLM inference for UC Santa Cruz. Zero-data-retention.",
  "api_key_env": "BAYLEAF_API_KEY",
  "base_url": "https://api.bayleaf.dev/v1/chat/completions",
  "models": [
    {
      "name": "${model}",
      "context_limit": 128000,
      "max_tokens": 16384${costRaw ? `,
      "input_token_cost": ${costRaw.prompt},
      "output_token_cost": ${costRaw.completion}` : ''}
    }
  ],
  "supports_streaming": true
}
${fence}

### 2. Store the API key

Run ${bt}goose configure${bt}, select **BayLeaf API** from the provider list, and paste
your ${bt}sk-bayleaf-...${bt} key. Goose stores it in your system keychain.

Alternatively, set ${bt}BAYLEAF_API_KEY${bt} in your environment for the session.

### 3. Use the model

${fence}bash
GOOSE_PROVIDER=bayleaf GOOSE_MODEL=${model} goose session
${fence}

Or for non-interactive use:

${fence}bash
GOOSE_PROVIDER=bayleaf GOOSE_MODEL=${model} goose run --text "Help me refactor this code"
${fence}

` + (gwsEnabled ? buildGwsSection(email, bt, fence) : '') + buildCanvasSection(bt, fence) + `
`;
}

// ── GWS section (inlined into SKILL.md when configured) ───────────

function buildGwsSection(email: string, bt: string, fence: string): string {
  return `---

## Google Workspace CLI

BayLeaf distributes credentials for the [Google Workspace CLI](https://github.com/googleworkspace/cli)
(${bt}gws${bt}), which gives agents access to Drive, Gmail, Calendar, Sheets, Docs, and other
Workspace services on behalf of the authenticated user. All operations run as ${bt}${email}${bt}.

### Installation

${fence}bash
npm install -g @googleworkspace/cli
gws --version
${fence}

### Download the OAuth client configuration

The client configuration identifies the BayLeaf GCP project (Internal consent screen
scoped to ${bt}@ucsc.edu${bt}). It is not a credential: the security comes from the OAuth
browser consent flow in the next step.

${fence}bash
mkdir -p ~/.config/gws
curl -s https://api.bayleaf.dev/docs/gws-client-secret.json \\
  -H "Authorization: Bearer sk-bayleaf-..." \\
  -o ~/.config/gws/client_secret.json
${fence}

On the campus network, the ${bt}-H${bt} header can be omitted.

### Authenticate (interactive, one-time)

This opens a browser window where ${email} grants OAuth consent.
**The user must do this step themselves** (it cannot be automated by the agent).

${fence}bash
gws auth login --account ${email} --full
${fence}

The ${bt}--full${bt} flag requests broad scopes (Drive, Gmail, Calendar, Sheets, Docs,
Slides, Tasks). Credentials are stored encrypted on disk and refresh automatically.

### Verify

${fence}bash
gws drive files list --params '{"q": "\\"root\\" in parents and trashed=false", "pageSize": 5, "fields": "files(id,name)"}'
${fence}

### Common services

| Service | Example |
|---------|---------|
| **Drive** | ${bt}gws drive files list --params '{"q": "...", "pageSize": 10, "fields": "files(id,name)"}'${bt} |
| **Gmail** | ${bt}gws gmail users messages list --params '{"userId": "me", "maxResults": 5}'${bt} |
| **Calendar** | ${bt}gws calendar events list --params '{"calendarId": "primary", "maxResults": 5, "singleEvents": true, "orderBy": "startTime", "timeMin": "..."}'${bt} |
| **Sheets** | ${bt}gws sheets spreadsheets values get --params '{"spreadsheetId": "...", "range": "Sheet1!A1:C10"}'${bt} |
| **Docs** | ${bt}gws docs documents get --params '{"documentId": "..."}'${bt} |

Command discovery: ${bt}gws <service> --help${bt} or ${bt}gws schema <service>.<resource>.<method>${bt}.

### MCP server mode

${bt}gws${bt} can also run as an MCP server for tool-calling agents:

${fence}bash
gws mcp -s drive,gmail,calendar
${fence}

### Troubleshooting

- **401 auth error**: Re-run ${bt}gws auth login --account ${email} --full${bt}
- **403 API not enabled**: Contact the BayLeaf admin (the GCP project may need the API enabled)
- **Wrong account's data**: Check ${bt}gws auth list${bt} and ${bt}gws auth default${bt}
- **Token refresh fails**: Re-run the auth login command above
`;
}

// ── Canvas LMS section (always included in SKILL.md) ──────────────

function buildCanvasSection(bt: string, fence: string): string {
  return `---

## Canvas LMS

The [canvaslms CLI](https://pypi.org/project/canvaslms/) gives agents read/write
access to Canvas courses, assignments, grades, submissions, announcements, and pages.
Each user authenticates with their own Canvas access token (separate from the BayLeaf
API key).

### Installation

${fence}bash
pipx install canvaslms
pipx inject canvaslms cryptography
${fence}

### Configuration

The user must generate a Canvas access token themselves:
**Canvas > Profile > Settings > New Access Token**. The token is shown only once.

There are three ways to supply credentials (in priority order):

**Option 1: Interactive login** (stores in system keyring, works on all platforms):

${fence}bash
canvaslms login
${fence}

Enter ${bt}canvas.ucsc.edu${bt} as the hostname and paste the token when prompted.

**Option 2: Environment variables** (good for agents, no persistent config needed):

${fence}bash
export CANVAS_SERVER=canvas.ucsc.edu
export CANVAS_TOKEN=your_token_here
${fence}

**Option 3: Config file** (fallback if keyring is unavailable):

The config file location depends on the platform:

| Platform | Path |
|----------|------|
| macOS | ${bt}~/Library/Application Support/canvaslms/config.json${bt} |
| Linux | ${bt}~/.config/canvaslms/config.json${bt} |
| Windows | ${bt}%LOCALAPPDATA%\\dbosk@kth.se\\canvaslms\\config.json${bt} |

Contents:

${fence}json
{"canvas": {"host": "canvas.ucsc.edu", "access_token": "YOUR_CANVAS_TOKEN"}}
${fence}

### Verify

${fence}bash
canvaslms courses -i
${fence}

### Common commands

${fence}bash
# List courses (with Canvas IDs)
canvaslms courses -i
canvaslms courses -i "121"                    # filter by regex

# List students (with emails)
canvaslms users -c "COURSE_ID" -s -e

# List assignments
canvaslms assignments list -c "COURSE_ID"

# View assignment details (rubric, description)
canvaslms assignments view -c "COURSE_ID" -a "assignment-regex"

# List submissions (ungraded only)
canvaslms submissions list -c "COURSE_ID" -a "assignment-regex" -U

# Grade a submission
canvaslms grade -c "COURSE_ID" -a "assignment-regex" -u "^student@" -g 7 -m "Comment"

# Post an announcement
canvaslms discussions announce -c "COURSE_ID" -m "Body text" "Title"

# List pages
canvaslms pages list -c "COURSE_ID"
${fence}

### Important notes

- **Course matching**: ${bt}-c${bt} accepts a regex and may match multiple courses across quarters.
  Always resolve to a numeric Canvas ID first with ${bt}canvaslms courses -i "pattern"${bt}.
- **Caching**: The CLI caches responses (submissions: 5 min, users: 2 days). Use
  ${bt}--no-cache${bt} after write operations.
- **Output format**: All output is TSV. Pipe through ${bt}cut${bt}, ${bt}awk${bt}, or ${bt}sort${bt} as needed.
- **Concluded courses**: Past-quarter courses don't appear in ${bt}canvaslms courses${bt}.
  Use the REST API to search: ${bt}curl "https://canvas.ucsc.edu/api/v1/courses?state[]=completed&search_term=..."${bt}
- **REST API fallback**: For operations the CLI doesn't support (creating assignments,
  file uploads, bulk operations), use ${bt}curl${bt} against ${bt}https://canvas.ucsc.edu/api/v1${bt}
  with ${bt}Authorization: Bearer TOKEN${bt}. API docs: https://canvas.instructure.com/doc/api/
`;
}
